// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (action) {
            return /* record */[/* count */state[/* count */0] - 1 | 0];
          } else {
            return /* record */[/* count */state[/* count */0] + 1 | 0];
          }
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Increment */0);
                    })
                }, "inc"), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Decrement */1);
                    })
                }, "dec"), React.createElement("div", undefined, String(match[0][/* count */0])));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
