// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Form$YourProjectName from "./Form.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Form$YourProjectName.make, { }), "root");

export {
  
}
/*  Not a pure module */
